### ISSUE TITLE
Change to anonymous function

### ISSUE THREAD

**Issue by c3ho** [Niaz-Ul-Haque/nlinks#3]
https://github.com/Niaz-Ul-Haque/nlinks/blob/adff79502af6a717ba978ebd69f09b5a06447cda/src/cli.js#L47-L84

Since you called this simple, I'm pretty sure you just want to execute it. Check this link https://www.javascripttutorial.net/javascript-anonymous-functions/ and the section under `immediately invoked function execution`. This way you can just use 
```
(() => {
  //code here
})()
```
without having to call it `function simple` or having to call `simple()`

**Comment by Niaz-Ul-Haque** [comment]
I see, did not know there is a way to do that. Thanks, ill check that out, get comfortable, and implement it. Thanks for pointing it out.

EDIT: I looked at it. But, the way I implemented it was with the async/await syntax. When I tried to make it an anonymous function. it's giving an error due to the await. cant have await without async. Please do comment if you have a solution to this as it is my first time working with an anonymous function

**Comment by c3ho** [comment]
Oh, it'll look something more or less like this. Just take the code inside `simple()` and put it inside where I had `//code here`
```
(() => {
const results = await link.check({ 
 					path: myArray, 
 				}); 
 				switch (results.links[0].status) { 
 					case 200: 
 						msg = "GOOD"; 
 						console.log( 
 							chalk.green( 
 								`${i++} = ${msg} == ${results.links[0].status} => ${ 
 									results.links[0].url 
 								}` 
 							) 
 						); 
 						break; 
 					case 404: 
 					case 400: 
 						msg = "BAD"; 
 						console.log( 
 							chalk.red( 
 								`${i++} = ${msg} == ${results.links[0].status} => ${ 
 									results.links[0].url 
 								}` 
 							) 
 						); 
 						break; 
 					default: 
 						msg = "UNKNOWN"; 
 						console.log( 
 							chalk.white( 
 								`${i++} = ${msg} == ${results.links[0].status} => ${ 
 									results.links[0].url 
 								}` 
 							) 
 						); 
 				} 
})()
```
You won't need to call `simple()`  or the function at the end because we're calling it with the `()` at the end
