### ISSUE TITLE
question about 3 lines

### ISSUE THREAD

**Issue by sanji11** [Niaz-Ul-Haque/nlinks#9]
I did not understand what is happening here. Can you please explain?

- Why are you calling the match twice? 
- If the array is null, what do you mean by "continue"?

https://github.com/Niaz-Ul-Haque/nlinks/blob/master/src/cli.js#L42-L44

**Comment by Niaz-Ul-Haque** [comment]
Ohh let me tell you what I did there.
a) ```let myArray = line.match(link_reg);``` 
-- what this code line does is, the ```line``` you see it the entire line of a file. It can be anything, but if there's a link somewhere in that line and matches my regex, it will be assigned to myArray variable. I am calling the match twice because the first match takes anything that looks like a link, and the second one takes the first link only if by chance there are 2 links in a single line. so only one will be taken.

b)```if (myArray == null) continue;```
``` myArray = line.match(link_reg)[0];``` ```//([0], taking the first website link (if only there is more than 2 links in a single line))```
-- What these 2 lines of code and the if statement does is, it checks if my variable is null or not. As you can see above (a point), if there's no match of a link in my line, ```myArray``` variable will get assigned a null value. so what the``` if ```statement does, is it checks if its null or not. If its null, I continue. continue means "Break out of the current value in the loop and start the next value" . So that way my program doesn't crash as the values that are null won't get sent to my program.

**Comment by sanji11** [comment]
oh, got it! Thanks a lot  for clear explanation:)
